# baseurl for gh-pages
# baseurl: '/yello'
baseurl: ''
exclude: ['node_modules', 'package.json', 'gulpfile.js', 'src']

paginate: 1
permalink: '/:title'

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'application'

